language: node_js
node_js:
- '10'
before_install:
- npm i -g typescript
- npm i -g npm-check-updates
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: me@unsmart.co
  api_key:
    secure: BaPTZRGPVU5l0YepZyT5ye+NimDSt6H1+7U8mxAtlIn5oPAzl+Zc47WlzwMdpJy5Rgd114lvF4agX06yhyA4tYX+gyBsWcpAXoMwXGk6x/M61Bw4/n6ercrt7DsAs2huK5rvjRPfWjl6XTCD479/lKIPHL3M4qOwGXjYuzOdIIn5TcnJBqWTARAKeXISemGrYfXBXDXnbM6j+hSP6Yc6WsxsjEc/n3iuvQVZX7lJdJiAl0xDRFjTO24SkSaEDaDCJ3hNwyE2tUx2EBPvhrr1G+CI+eOkwQIt5+1h32pekT2QJulSt+hadNgw5et7WNVLZNKugnwKeZcV/N+HYENI8X3sbFath/qEPzGk07LQgZKa2UFcCU5yL4JWx3Vj6qnFO7Xxjmms9zgVUGn5Nd6VbRGEUybPm6e0BgbRpqUOk24pgYEEuS0bptZsYQZXEt2gZKG4JKYcU44ZVpACNe8pjM/y8rJCSzFmvVw5wiA8urOuFg0jMh6pz3TLxh4ZP0vXzvqOXIIAt2ty0SfkLRRAs8Qe7QqBxjN76ytiV0bfkn7jrh4klqZ2fHdRvhxapSFMmSrq0SuegXgeK0LNi6l1TjuqEbxBn7qehyFLBrhtFZ+FVE76KiuNjsWoaXBQZsg969ITSXKSp/01A8/g/2fnaVE0OwRw6PYhxlEer0/S9ck=
  on:
    branch: master
